name: duruwa
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^2.2.1
  floating_search_bar: ^0.3.0
  flutter_svg: ^0.18.0
  #provider: ^4.3.2
  flutter_gifimage: ^1.0.1
  flutter_dialogflow: ^0.1.3
  cloud_firestore: 0.14.1+3
  firebase_auth: ^0.18.3
  #firebase_auth: ^0.14.0+5
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12+4
  logger: ^0.9.4
  firebase_database: ^4.1.1
  firebase_core: ^0.5.0+1
  splashscreen: 1.2.0
  flutter_signin_button: ^1.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/cimage1.jpg
    - assets/images/cimage2.jpg
    - assets/images/cimage3.jpg
    - assets/images/cimage4.jpg
    - assets/images/cimage5.jpg
    - assets/images/cimage6.jpg
    - assets/images/splash_logo.jpg
    - assets/images/splash_loading.gif
    - assets/images/onboard1.jpg
    - assets/images/onboard2.jpg
    - assets/images/onboard3.jpg
    - assets/icons/profile_background_circle.png
    - assets/jsonfile/b--xarl-68433cee6063.json # airport_airgroundposition 항공지상직
    - assets/jsonfile/d--jskk-df24c9973de1.json # airport_dutyfreeshop 항공면세점
    - assets/jsonfile/n--pmhx-fda9826c1a11.json # airport_pilot 항공 파일럿
    - assets/jsonfile/newagent-wpthph-3a8497d159c7.json # airport_Stewardess 항공 승무원
    - assets/jsonfile/w----hr9x-ac2b59909a30.json # civilservant_correctional 공무원 교정직
    - assets/jsonfile/m----my9v-4960ccac2b60.json # civilservant_firefighting 공무원 소방원
    - assets/jsonfile/t----g9wx-8484a14d0e87.json # civilservant_socialwelfare 공무원 사회복지직
    - assets/jsonfile/r----jlgh-9e013f980926.json # civilservant_education 공무원 교육직
    - assets/jsonfile/webdeveloper-hupp-239eb853d65c.json # Webdeveloper IT 웹개발
    - assets/jsonfile/t--tcpm-cf4c8ea2a638.json # IT_Applicationprogrammer IT 응용프로그래머
    - assets/jsonfile/w----hr9x-ac2b59909a30.json # WEBDSGN IT 웹디자이너
    - assets/jsonfile/network-server-security-jdyv-2291aa0df913.json # network&server&security IT 네크워크/서버/보안
    - assets/jsonfile/newagent-txjy-790a0e52da16.json # financial&accounting 금융회계
    - assets/jsonfile/personnel-general-affairs-jnes-aad4a7a81d65.json # personnel&general_affairs 총무
    - assets/jsonfile/planning-office-vqqj-332600fb0749.json # planning&office 기획부
    - assets/jsonfile/production-quality-contro-prfq-3de2d6fd4c46.json # production&quality&control 품질관리
    - assets/jsonfile/b--xarl-2641a7cda6e6.json
    - assets/jsonfile/d--jskk-729cfe3ca586.json
    - assets/jsonfile/m----my9v-223a0c87700d.json
    - assets/jsonfile/newagent-wpthph-076c84be91ae.json
    - assets/jsonfile/n--pmhx-7687be1925b9.json
    - assets/jsonfile/r----jlgh-c200ca4aaf19.json
    - assets/jsonfile/t----g9wx-06409c59f0c7.json
    - assets/jsonfile/t--tcpm-c7c9dcc6c4f9.json
    - assets/jsonfile/w----hr9x-6c9d646d2cb7.json
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#  fonts:
#    - family: Schyler
#      fonts:
#        - asset: fonts/Schyler-Regular.ttf
#        - asset: fonts/Schyler-Italic.ttf
#          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
